Instructions
Please submit your homework in the form of a Matlab script called assign2_<userid>.m,...
    where <userid> is your UCD Kerberos login. E.g. assign2_pjanata.m
Your homework will be graded on completeness (60%), organization/clarity (40%)...
Completeness just means that you did it all, or at least tried it all...
    Organization/clarity means that the code is legible and it is easy to...
    tell what part of the code is dealing with what part of the assignment, i.e. use comments.
Note: If your assignment is late, you will not get credit for it
You can solve many of the problems by looking at the lecture notes. ..
 Learning how to program effectively has a lot to do with developing...
    procedural memory for writing expressions. In other words, you will...
    learn how to program better if you complete all of the problems by...
    actually typing in the lines of code rather than copying and pasting.
Vectors
1.	Create a row vector of numbers starting at 67 and ending at 84,...
    incrementing by 1.
2.	Create a column vector starting at 0 and ending at -10.
3.	Create a row vector starting with 15 and counting by 10s up to 155.
4.	Create a column vector starting at 3 and counting by 3s up to 45.
5.	Create a row vector starting at 10 and counting backward by 2 until -10.
6.	Create a row vector that begins at -1 and ends at +1, incrementing by 0.05.
7.	Create a row vector that starts at -13.2 and increments by 3.3 all...
    the way up to 33,000.
Matrices
1.	Create a variable containing a 4x7 matrix (4 rows, 7 columns) in which...
    the 1st column is filled with 1, the 2nd column with 2, etc.
2.	Create a variable containg a 6x8 matrix in which the values in the...
    first column start with 1 and increment by 1, the values in the 2nd...
    column start with 2 and increment by 2, etc.
3.	Create a row vector in which the numbers are incrementing by two from...
    0 to 98. Then figure out how to use the reshape() function (type "help...
    reshape" for information on how to use the reshape function) on that...
    vector to create a 5x10 matrix in which the numbers going down columns...
    increment by two (shown here for the first 3 columns)...
    :?0 10 20?2 12 22?4 14 24?6 16 26?8 18 28
4.	Create a row vector containing the numbers 1, 3, 4 and 8 and store...
    the result in a variable that you have decided to call "column_indices."
Indexing
1.	Practice indexing into arrays using the 6x8 matrix you created in...
    Matrices, Step 2 above. Complete each of the following steps using ...
    only a single line of code.
1.	Extract the 3rd row.
2.	Extract the even-numbered columns.
3.	Extract the 1st, 3rd, 4th, and 8th columns using the column_indices...
    variable that you created in the preceding section.
4.	Extract the 2nd row of the 6th column
5.	Create a vector beginning with 1, skipping by 4 and ending at 45.
6.	Use this vector to index into your 6x8 matrix. What's the result?...
Is it what you were expecting? If not, can you figure out why you got the...
    answer you did? Hint: There are two ways to index values in a matrix:...
    subscripts and indices.
2.	For 1 point of extra credit. Let's say you only want to extract...
values from the following three coordinates (pairs of row and column...
     subscripts) in your matrix: (3,6); (2,1); (4,8). Try to do this with...
    as few lines as possible. Hint: You will need to use one of Matlab's ...
matrix manipulation functions to do this. This function (and its reverse...
    sibling) convert between the two ways of specifying locations within...
    a matrix. Type 'help elmat' and look through the list of functions in...
    the Matrix manipulation sub-category to find the function that will...
    do the appropriate conversion for you.
String construction
1.	Place your first name in a variable
2.	Place your last name in another variable
3.	Using the two variables that you just made, create a third variable...
    that has your last name, first name, e.g. "Janata, Petr"
4.	Create a numeric vector with your birthday, i.e. the values...
    correspond to the month, day, and year.
5.	Using the strings and numeric vector you just created, create a...
    string that has your name followed by a colon and then your birthdate,...
    e.g. Janata, Petr: 9 2 67 (hint: you may want to find a function that...
    converts a num to a str)
Get a jump on next week (not graded for this assignment)
1.	Print your name and birthday to the command window using fprintf()....
    Don't just use fprintf to print the string you created in Step 5. ...
Rather, use fprintf with a format string that specifies the printing ...
    of each individual variable.
